on:
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo ${{ vars.MY_VARIABLE }}
      - name: Print secret
        run: echo ${{ secrets.MY_SECRET }}
